import { test, expect } from '@playwright/test'

test('注册、登录、对话、选文展开、登出与再登录数据保持', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Concept Branch' })).toBeVisible()
  await expect(page.getByRole('button', { name: '登录', exact: true })).toBeVisible()

  await page.getByRole('button', { name: '注册一个' }).click()
  await page.getByLabel('用户名').fill('e2e-user')
  await page.getByLabel('密码').fill('e2e-pass-1234')
  await page.getByRole('button', { name: '注册', exact: true }).click()
  await expect(page.getByText('e2e-user')).toBeVisible()
  await expect(page.getByRole('button', { name: '切换界面风格' })).toHaveCount(0)
  await expect(page.locator('.style-picker, .style-menu')).toHaveCount(0)
  await expect(page.locator('.app-shell')).toHaveAttribute('style', /--left-width: 280px/)

  await page.getByRole('button', { name: '模型与中转站' }).click()
  await page.getByLabel('API base URL').fill(process.env.CONCEPT_BRANCH_E2E_PROVIDER_URL || 'http://127.0.0.1:9432/v1')
  await page.getByRole('textbox', { name: '模型', exact: true }).fill('mock-model')
  await page.getByLabel('API key').fill('e2e-test-key')
  await page.getByRole('button', { name: '测试并保存 Provider' }).click()
  await expect(page.getByRole('status')).toContainText('Provider 已安全保存')
  await page.getByRole('button', { name: '重命名 新的中转站' }).click()
  await page.getByLabel('新的中转站 名称').fill('本地测试 Provider')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Provider 名称已更新')
  await page.getByRole('dialog').getByRole('button', { name: '×' }).first().click()
  await expect(page.locator('.provider-dock')).toContainText('本地测试 Provider')
  await expect(page.locator('.conversation header').getByLabel('活动 Provider')).toHaveCount(0)
  const initialThemeLabel = await page.getByRole('button', { name: /切换(浅色|深色)模式/ }).getAttribute('aria-label')
  await page.getByRole('button', { name: initialThemeLabel }).click()
  await expect(page.getByRole('button', { name: initialThemeLabel === '切换浅色模式' ? '切换深色模式' : '切换浅色模式' })).toBeVisible()
  await page.getByRole('button', { name: initialThemeLabel === '切换浅色模式' ? '切换深色模式' : '切换浅色模式' }).click()
  const leftHandle = page.getByRole('separator', { name: '会话栏宽度' })
  const handleBox = await leftHandle.boundingBox()
  if (!handleBox) throw new Error('left resize handle not found')
  await page.mouse.move(handleBox.x + handleBox.width / 2, handleBox.y + 80)
  await page.mouse.down()
  await page.mouse.move(handleBox.x + 35, handleBox.y + 80)
  await page.mouse.up()
  await expect.poll(() => page.locator('.app-shell').evaluate((element) => Number.parseFloat(element.style.getPropertyValue('--left-width')))).toBeGreaterThan(220)
  await page.getByRole('button', { name: '收起会话栏' }).click()
  await expect(page.locator('.discussions')).toHaveClass(/is-collapsed/)
  await page.getByRole('button', { name: '显示会话栏' }).click()
  await page.getByRole('button', { name: '收起分支栏' }).click()
  await expect(page.locator('.tree-panel')).toHaveClass(/is-collapsed/)
  await page.getByRole('button', { name: '显示分支栏' }).click()

  page.once('dialog', (dialog) => dialog.accept('优化想法'))
  await page.getByRole('button', { name: '新建讨论' }).click()
  await expect(page.getByText('优化想法', { exact: true })).toBeVisible()
  await page.getByLabel('上传背景文件').click()
  await page.locator('input[type="file"]').setInputFiles({ name: 'background.txt', mimeType: 'text/plain', buffer: Buffer.from('背景资料：训练过程需要稳定的优化策略。') })
  await expect(page.getByLabel('背景文件', { exact: true })).toContainText('background.txt')
  await page.getByLabel('消息', { exact: true }).fill('请解释训练过程')
  await page.getByLabel('消息', { exact: true }).press('Enter')
  await expect(page.locator('article.user').last()).toContainText('请解释训练过程')
  await expect(page.locator('.message-state')).toContainText('已发送，正在等待回答')
  await expect(page.getByTestId('messages')).toContainText('梯度下降')
  await expect(page.locator('.avatar')).toHaveCount(0)
  await expect(page.getByTestId('messages').locator('pre')).toContainText('loss.backward()')
  await expect(page.getByTestId('messages').locator('img')).toHaveCount(0)

  const userMaterial = page.locator('article.user').last()
  await userMaterial.locator('.bubble').evaluate((element) => {
    const node = element.querySelector('p')?.firstChild
    const start = node?.textContent.indexOf('训练过程') ?? -1
    if (!node || start < 0) throw new Error('user material target not found')
    const range = document.createRange(); range.setStart(node, start); range.setEnd(node, start + 4)
    const selection = window.getSelection(); selection.removeAllRanges(); selection.addRange(range)
    element.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }))
  })
  await expect(page.getByText('从我的背景材料提问')).toBeVisible()
  await page.getByRole('button', { name: '自定义问题' }).click()
  await page.getByLabel('自定义问题').fill('这段背景是什么意思？')
  await page.getByRole('button', { name: '展开' }).click()
  await expect(page.getByRole('button', { name: '返回父卡片' })).toBeVisible()
  await expect(page.getByLabel('背景文件', { exact: true })).toContainText('继承')
  await expect(page.locator('article.user').last()).toContainText('这段背景是什么意思？')
  await page.getByRole('button', { name: '返回父卡片' }).click()
  await expect(page.getByTestId('messages')).toContainText('请解释训练过程')

  const assistant = page.locator('article.assistant').last()
  await assistant.locator('.bubble').evaluate((element) => {
    const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT)
    let node
    while ((node = walker.nextNode())) {
      const start = node.textContent.indexOf('梯度下降')
      if (start >= 0) {
        const range = document.createRange(); range.setStart(node, start); range.setEnd(node, start + 4)
        const selection = window.getSelection(); selection.removeAllRanges(); selection.addRange(range)
        element.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }))
        return
      }
    }
    throw new Error('target text not found')
  })
  await expect(page.getByRole('button', { name: '直接解释' })).toBeVisible()
  await page.getByRole('button', { name: '直接解释' }).click()
  await expect(page.getByRole('button', { name: '返回父卡片' })).toBeVisible()
  await expect(page.locator('.tree-node.active')).toContainText('梯度下降')
  await page.getByLabel('消息', { exact: true }).fill('继续追问')
  await page.getByRole('button', { name: '发送' }).click()
  await expect(page.locator('article.user').last()).toContainText('继续追问')

  await page.getByRole('button', { name: '返回父卡片' }).click()
  await expect(page.getByTestId('messages')).toContainText('请解释训练过程')
  await expect(page.getByTestId('messages')).not.toContainText('继续追问')
  await page.reload()
  await expect(page.getByText('优化想法', { exact: true })).toBeVisible()
  await expect(page.getByTestId('messages')).toContainText('请解释训练过程')
  await expect(page.locator('.tree-node')).toHaveCount(3)
  await page.getByLabel('搜索讨论和消息').fill('训练过程')
  await expect(page.locator('.search-results')).toContainText('请解释训练过程')
  await page.locator('.search-result').filter({ hasText: '请解释训练过程' }).first().click()
  await expect(page.getByTestId('messages')).toContainText('请解释训练过程')

  await page.getByRole('button', { name: '登出' }).click()
  await expect(page.getByRole('button', { name: '登录', exact: true })).toBeVisible()
  await page.getByLabel('用户名').fill('e2e-user')
  await page.getByLabel('密码').fill('e2e-pass-1234')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByText('e2e-user')).toBeVisible()
  await expect(page.getByText('优化想法', { exact: true })).toBeVisible()
  await expect(page.locator('.tree-node')).toHaveCount(3)
})
